---
- name: Show Version info of all switches 
  hosts: all
  tasks:
  - name: Show version of switches
    picos_config: mode='cli_show' cmd='show version'
    register: exec_result
  - name: Show execution result
    debug: var=exec_result.stdout_lines