---
- name: Shows uptime info for all switches 
  hosts: all
  tasks:
  - name: Shows uptime info for all switches 
    picos_config: mode='shell' cmd='uptime'
    register: exec_result
  - name: Show execution result
    debug: var=exec_result.stdout_lines  