---
- name: Show CPU utilization all switches 
  hosts: all
  tasks:
  - name: Show CPU utilization all switches 
    picos_config: mode='shell' cmd='top -n 1 -b'
    register: exec_result
  - name: Show execution result
    debug: var=exec_result.stdout_lines
