---
- name: Configure SNMP v3 in switchess
  hosts: all 
  tasks:
  - name: Transfer the script
    copy: src=snmpv3.conf dest=/home/admin/snmpv3.conf force=yes mode=0777

  - name: Activate the configuration
    picos_config: mode='config_load' cmd='/home/admin/snmpv3.conf'
    register: exec_result

  - name: Show execution result
    debug: var=exec_result.stdout_lines
